### ISSUE TITLE
$ in code block

### ISSUE THREAD

**Issue by Glennmen** [dracula/draculatheme.com#72]
I was looking to add support for the Dracula Theme website in the [CodeCopy](https://github.com/zenorocha/codecopy) extension (also owned by @zenorocha) but noticed that a lot of the code blocks start with `$`, for example: https://draculatheme.com/xcode/

This causes the inconvenience of not being able to quickly copy/paste the command because `$` will give an error in the terminal. 

I will still add support for the Dracula Theme website soon, if you guys agree that `$` doesn't have any added benefit but time is an issue I could make a little time to make a PR for it. It shouldn't take too long to do.

**Comment by Glennmen** [comment]
Did some looking around and discovered a little trick that is being used on the DigitalOcean community pages. They use `<ul>` with a custom bullet icon. This way you won't copy `$`, even not when a user selecting all with his mouse.

More testing is needed but so far I have this:
HTML (only 1 `<li>` is required for single line code block):
```html
<pre>
	<code langs>
		<ul class="prefixed">
    		<li class="line" prefix="$">Prefixed</li>
    		<li class="line" prefix="$">Apples</li>
    		<li class="line" prefix="$">Oranges</li>
		</ul>
	</code>
</pre>
```

CSS:
```css
pre .prefixed {
    white-space: normal;
    margin: 0;
    font-size: 14px!important;
}

pre .line {
    padding: 0!important;
    list-style-type: none!important;
    white-space: pre;
    margin: 0 0 0 -5px!important;
    line-height: 1.5!important;
}

pre .line::before {
    -webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    -o-user-select: none;
    user-select: none;
    content: attr(prefix);
    text-align: right;
    display: inline-block;
    margin-right: 10px;
    margin-left: 5px;
}
```
